### ISSUE TITLE
Fix JK algorithm small miscalculation

### ISSUE THREAD

**Issue by psavery** [MolSSI-SSS/QM_2017_SSS_Team1#31]
The energy is off by a little bit. I think there is a small problem somewhere. Could you find it?

**Comment by ghost** [comment]
just had to 
change: aux = psi4.core.BasisSet.build(mol, fitrole="JKFIT", other=basis)
to: aux = psi4.core.BasisSet.build(mol, "DF_BASIS_SCF", fitrole="JKFIT", other=basis)
